name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Gh pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: production
          base_href: /ng-grid/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/ng-grid

permissions:
  contents: write
