name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
      - name: Use cached development node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: development-node_modules-${{ env.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            development-node_modules-${{ env.CACHE_VERSION }}-
            development-node_modules-
      - name: Install dependencies
        run: npm ci
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use cached development node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: development-node_modules-${{ env.CACHE_VERSION }}-${{ hashFiles('**/package-lock.lock') }}
          restore-keys: |
            development-node_modules-${{ env.CACHE_VERSION }}-
            development-node_modules-
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm run test:ci

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Gh pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: production
          base_href: /ng-grid/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/ng-grid

permissions:
  contents: write
